services:
  compressor:
    build:
      context: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      MINIO_ENDPOINT: 'minio'
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: '${MINIO_ACCESS_KEY}'
      MINIO_SECRET_KEY: '${MINIO_SECRET_KEY}'
